window.JOBTEST_NAMES = [
  { left: "Hale & Co. Supply", right: "Hale & Co. Supply", pick: "same" },
  { left: "Mira Chen Studio", right: "Mira Chen Studlo", pick: "diff" },
  { left: "Oakridge Transit", right: "Oakridge Transit", pick: "same" },
  { left: "J.P. Moreland", right: "J.P. Morelund", pick: "diff" },
  { left: "North Bay Electric", right: "North Bay Electic", pick: "" },
  { left: "Sable Finch Books", right: "Sable Finch Books", pick: "same" },
  { left: "Riverbend Optics", right: "Riverbend Optics", pick: "" },
  { left: "Toma + Voss Legal", right: "Toma + Voss Legal", pick: "same" },
  { left: "Delgado Produce", right: "Delagado Produce", pick: "diff" },
  { left: "Kestrel Bindery", right: "Kestrel Bindery", pick: "" },
  { left: "Pilar Quinn Dental", right: "Pilar Quinn Dental", pick: "" },
  { left: "West Hollow Freight", right: "West Holow Freight", pick: "" },
  { left: "Nash & Brier Mill", right: "Nash & Brier Mill", pick: "" },
  { left: "Lumen Park Clinic", right: "Lumen Park Clinc", pick: "" },
  { left: "Cinderlot Bakery", right: "Cinderlot Bakery", pick: "" },
  { left: "Arlo Vane Survey", right: "Arlo Vane Survey", pick: "" },
  { left: "Harborfinch Radio", right: "Harborfinch Radio", pick: "" },
  { left: "Moth & Needle Co.", right: "Moth & Neddle Co.", pick: "" },
  { left: "Juniper Toll Roads", right: "Juniper Toll Roads", pick: "" },
  { left: "Bexley Crane Works", right: "Bexely Crane Works", pick: "" },
  { left: "Orrin Hale Timber", right: "Orrin Hale Timber", pick: "" },
  { left: "Pearl Street Glass", right: "Pearl Street Glass", pick: "" },
  { left: "Vesper Yarn Depot", right: "Vespar Yarn Depot", pick: "" },
  { left: "Quill & Cedar Press", right: "Quill & Cedar Press", pick: "" },
  { left: "Iona Marsh Ceramics", right: "Iona Marsh Ceramics", pick: "" },
  { left: "Red Lantern Movers", right: "Red Lantren Movers", pick: "" },
  { left: "Bramble Court Inn", right: "Bramble Court Inn", pick: "" },
  { left: "Fenn & Oswald Lab", right: "Fenn & Oswald Lab", pick: "" },
  { left: "Coppervine Nursery", right: "Coppervine Nursery", pick: "" },
  { left: "Sora Patel Design", right: "Sora Patel Desgin", pick: "" },
  { left: "Nettle & Wick Soap", right: "Nettle & Wick Soap", pick: "" },
  { left: "Gull Point Marina", right: "Gull Point Marina", pick: "" },
  { left: "Ashford Bolt Co.", right: "Ashford Bolt Co.", pick: "" },
  { left: "Wren Hollow Audio", right: "Wren Holow Audio", pick: "" },
  { left: "Calder Mint Works", right: "Calder Mint Works", pick: "" },
  { left: "Lowtide Print Shop", right: "Lowtide Print Shop", pick: "" },
  { left: "Yarrow Field Seeds", right: "Yarrow Feild Seeds", pick: "" },
  { left: "Pim & Locke Travel", right: "Pim & Locke Travel", pick: "" },
  { left: "Ironspoon Catering", right: "Ironspoon Catering", pick: "" },
  { left: "Thea Ruiz Archive", right: "Thea Ruiz Archive", pick: "" },
  { left: "Mossback Canoes", right: "Mossback Canoes", pick: "" },
  { left: "Hearthline Stoves", right: "Hearthlne Stoves", pick: "" },
  { left: "Nico Bram Welding", right: "Nico Bram Welding", pick: "" },
  { left: "Silverfin Cannery", right: "Silverfin Cannery", pick: "" },
  { left: "Dusk & Rowan Film", right: "Dusk & Rowan Film", pick: "" },
  { left: "Maplewick Lanterns", right: "Maplewick Lanterns", pick: "" },
  { left: "Oatley Grain Exchange", right: "Oatley Grain Exhange", pick: "" },
  { left: "Rook Street Bicycles", right: "Rook Street Bicycles", pick: "" },
  { left: "Lila Cho Hydrology", right: "Lila Cho Hydrology", pick: "" },
  { left: "Cinder & Flint Tools", right: "Cinder & Flint Tools", pick: "" },
  { left: "Pebbleford Library", right: "Pebbleford Library", pick: "" },
  { left: "Vale & Orchard CSA", right: "Vale & Orchard CSA", pick: "" },
  { left: "Thornwell Hardware", right: "Thornwell Hardwear", pick: "" },
  { left: "Emberlot Theater", right: "Emberlot Theater", pick: "" },
  { left: "Sable Key Charters", right: "Sable Key Charters", pick: "" },
  { left: "Quinn Adler Survey", right: "Quinn Adler Survey", pick: "" },
  { left: "Northfen Apiary", right: "Northfen Apiary", pick: "" },
  { left: "Brickle & Sons Tile", right: "Brickle & Sons Tile", pick: "" },
  { left: "Harborlight Clinic", right: "Harborlight Clinc", pick: "" },
  { left: "Willa Frost Atelier", right: "Willa Frost Atelier", pick: "" },
  { left: "Pinekettle Coffee", right: "Pinekettle Coffee", pick: "" },
  { left: "Osprey Dock Repair", right: "Osprey Dock Repair", pick: "" },
  { left: "Merrick Oven Works", right: "Merrick Oven Works", pick: "" },
  { left: "Cinderwell Paper", right: "Cinderwel Paper", pick: "" },
  { left: "Rook & Plover News", right: "Rook & Plover News", pick: "" },
  { left: "Ada Voss Mapping", right: "Ada Voss Mapping", pick: "" },
  { left: "Goldthread Tailors", right: "Goldthread Tailors", pick: "" },
  { left: "Basin Street Grocers", right: "Basin Street Grocers", pick: "" },
  { left: "Fennelwick Dairy", right: "Fennelwick Dairy", pick: "" },
  { left: "Holt & Brine Smokehouse", right: "Holt & Brine Smokehouse", pick: "" },
  { left: "Nimble Cart Freight", right: "Nimble Cart Freigt", pick: "" },
  { left: "Iris Lang Ceramics", right: "Iris Lang Ceramics", pick: "" },
  { left: "Redkettle Foundry", right: "Redkettle Foundry", pick: "" },
  { left: "Cove & Ladder Paint", right: "Cove & Ladder Paint", pick: "" },
  { left: "Sora Field Botanics", right: "Sora Field Botanics", pick: "" },
  { left: "Parchment Owl Press", right: "Parchment Owl Press", pick: "" },
  { left: "Bram Shore Survey", right: "Bram Shore Survay", pick: "" },
  { left: "Littlefen Orchards", right: "Littlefen Orchards", pick: "" },
  { left: "Kite & Barrel Imports", right: "Kite & Barrel Imports", pick: "" },
  { left: "Nova Reed Lighting", right: "Nova Reed Lighting", pick: "" },
  { left: "Ashenford Quarries", right: "Ashenford Quarries", pick: "" },
  { left: "Tallow & Wick Co.", right: "Tallow & Wick Co.", pick: "" },
  { left: "Mira Sol Transit", right: "Mira Sol Transit", pick: "" },
  { left: "Greenkiln Pottery", right: "Greenkiln Pottery", pick: "" },
  { left: "Harrow Finch Music", right: "Harrow Finch Music", pick: "" },
  { left: "Pebble & Thorn Land", right: "Pebble & Thorn Land", pick: "" },
  { left: "Orrin Street Pharmacy", right: "Orrin Street Pharmacy", pick: "" },
  { left: "Cinderlot Records", right: "Cinderlot Recrods", pick: "" },
  { left: "Vale Harbor Pilots", right: "Vale Harbor Pilots", pick: "" },
  { left: "Nettlebridge Mill", right: "Nettlebridge Mill", pick: "" }
];
